name: Python Docker Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  # 1. First Job: Security Scan (The Gatekeeper)
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important: Gitleaks & SonarCloud need the full history

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # --- SAST INTEGRATION (Updated Action) ---
      - name: SonarCloud Scan
        if: always() # Runs this scan even if Gitleaks finds a secret and fails
        uses: SonarSource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "https://sonarcloud.io"
        with:
          args: >
            -Dsonar.organization=talhailyasdev
            -Dsonar.projectKey=talhailyasdev_ads-project-2026

  # 2. Second Job: Docker Build
  build:
    needs: security-scan # CRITICAL: This stops the build if secrets or bad code are found!
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build the Docker Image
        run: docker build -t ads-app:latest .