name: Python Docker Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  # 1. First Job: Security Scan (The Gatekeeper)
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important: Gitleaks & SonarCloud need the full history

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # --- SAST INTEGRATION ---
      - name: SonarCloud Scan
        if: always() # Runs this scan even if Gitleaks finds a secret and fails
        uses: SonarSource/sonarqube-scan-action@master 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # 2. Second Job: Docker Build & Security Scans (Trivy + ZAP)
  build:
    needs: security-scan # CRITICAL: This stops the build if secrets or bad code are found!
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build the Docker Image
        run: docker build -t ads-app:latest .

      # --- WEEK 3 Phase 2: TRIVY CONTAINER SCAN ---
      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ads-app:latest'
          format: 'table'
          exit-code: '1' # CRITICAL: This forces the pipeline to FAIL if it finds a vulnerability
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      # --- WEEK 3 Phase 3: OWASP ZAP DAST SCAN ---
      # 1. Start the container in the background so ZAP has something to attack
      - name: Start Application Container
        run: docker run -d -p 5000:5000 --name test-app ads-app:latest

      # 2. Give the web server 10 seconds to wake up
      - name: Wait for server to start
        run: sleep 10

      # 3. Attack the running app with ZAP
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:5000'
          fail_action: false # Generates a report without crashing the pipeline initially